# Generated by Django 3.2.16 on 2023-01-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='images/talaba')),
                ('sarlavha', models.CharField(help_text='Matn', max_length=100)),
                ('vaqt', models.DateField()),
                ('text', models.TextField(help_text='Matn')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Postlar',
            },
        ),
    ]
